### ISSUE TITLE
[ppa-experiment] Please confirm that if Telemetry is disabled, PPA is automatically disabled as well (as indicated by Mozilla CTO on reddit)

### ISSUE THREAD

**Issue by xe-3** [mozilla/explainers#14]
From Bobby Holly (Mozilla CTO):
> That's right. The prototype is built on top of the telemetry subsystem (using a separate DAP endpoint) ***so disabling telemetry disables the whole thing.***
>[...]
> The UI doesn't indicate it but that's how it works under the hood. I'll see if we can gray it out in the next release to make that more clear.

[Context](https://www.reddit.com/r/firefox/comments/1e43w7v/comment/lde59eq/)

Can you please confirm the accuracy of these statements. I see no indication (in the GUI, nor in About:config) that PPA is disabled when Telemetry is disable. I have no reason to distrust the assertion made, But I would like confirmation that the statement is technically accurate.

And for users with Telemetry disabled, does this comment from @martinthomson still apply:
> The API appears to function fully when someone is opted out, but no private information is released. That is, saveImpression appears to save something (but saves nothing), and measureConversion generates a measurement message that contains all zero values. From the perspective of the sites involved, things appear to be exactly the same as someone who has the feature enabled.
>
>Our explainer should really cover this, but it doesn't, so I'll use this issue to track the addition of the above explanation to the explainer.

**Comment by bgrins** [comment]
Yes, these statements are accurate - the PPA prototype is disabled when telemetry is disabled. The UI in about:preferences has now been fixed to indicate this in https://bugzilla.mozilla.org/show_bug.cgi?id=1908312 (and should be visible in the latest Nightly)
